### ISSUE TITLE
Task List 12.06.2022-18.06.202

### ISSUE THREAD

**Issue by SkivHisink** [SkivHisink/MasterWork#6]
Необходимо:
1) Изучить

- [ ] https://www.projectpro.io/article/how-to-build-arima-model-in-python/544
- [ ] https://www.machinelearningplus.com/time-series/arima-model-time-series-forecasting-python/
- [ ] https://machinelearningmastery.ru/arima-for-time-series-forecasting-with-python/ (не одинаковый ли контент?)
- [ ] https://towardsdatascience.com/forecast-with-arima-in-python-more-easily-with-scalecast-35125fc7dc2e
- [ ] https://pythobyte.com/arima-model-demonstration-779c8418/
- [ ] https://machinelearningmastery.com/arima-for-time-series-forecasting-with-python/
- [ ] https://www.justintodata.com/arima-models-in-python-time-series-prediction/
- [ ] https://www.javatpoint.com/arima-model-in-python
- [ ] https://economy.bsu.by/wp-content/uploads/2016/10/naft_ar_ma.pdf
- [ ] https://www.biconsult.ru/products/model-arima-v-mashinnom-obuchenii
- [ ] https://habr.com/ru/post/553658/
- [ ] https://github.com/AlexanderPetrenko83/Articles/tree/master/20210421_Time-series
- [ ] https://github.com/AlexanderPetrenko83/Articles/blob/master/20210421_Time-series/210419_AR_NN.ipynb
- [ ] https://romanorac.github.io/machine/learning/2019/09/27/time-series-prediction-with-lstm.html
- [ ] https://www.youtube.com/watch?v=enpPFqcIFj8&list=PLlb7e2G7aSpRb95_Wi7lZ-zA6fOjV3_l7&index=1
- [ ] https://habr.com/ru/company/ods/blog/327242/
- [ ] https://habr.com/ru/post/477206/
- [ ] https://habr.com/ru/post/210530/
- [ ] https://habr.com/ru/post/693562/
- [ ] https://habr.com/ru/post/207160/
- [ ] https://habr.com/ru/post/559796/
- [ ] https://habr.com/ru/post/659405/
- [ ] https://habr.com/ru/post/447714/
- [ ] https://habr.com/ru/post/559062/

**Comment by SkivHisink** [comment]
Добавлено https://www.sciencedirect.com/science/article/pii/S1877050922013382

**Comment by SkivHisink** [comment]
Вроде схожее http://uu.diva-portal.org/smash/get/diva2:1683696/FULLTEXT01.pdf

> Добавлено https://www.sciencedirect.com/science/article/pii/S1877050922013382

**Comment by SkivHisink** [comment]
Пока одна из тех статей, где есть какое-то продвижение. 
https://towardsdatascience.com/forecast-with-arima-in-python-more-easily-with-scalecast-35125fc7dc2e

**Comment by SkivHisink** [comment]
https://habr.com/ru/company/ods/blog/327242/ Неплохая статья стоит перечитать позже ещё разок.

**Comment by SkivHisink** [comment]
https://habr.com/ru/post/207160/ есть полезная информация по подготовке данных.

**Comment by SkivHisink** [comment]
https://habr.com/ru/post/553658/ Статья средней информативности, но имеет код как для аримы, так и для нейронки однослойной. Стоит посмотреть.

**Comment by SkivHisink** [comment]
https://habr.com/ru/post/659405/ эта статья - перевод данной статьи https://towardsdatascience.com/forecasting-atmospheric-co2-concentration-with-python-c4a99e4cf142
 На эту статью тоже стоит обратить внимание.

**Comment by SkivHisink** [comment]
https://habr.com/ru/company/ods/blog/323730/ интересная статья. Можно оттуда взять тоже прогнозатора.

**Comment by SkivHisink** [comment]
https://habr.com/ru/company/sbermegamarket/blog/692392/ неплохая статья.

**Comment by SkivHisink** [comment]
https://romanorac.github.io/machine/learning/2019/09/27/time-series-prediction-with-lstm.html код поднять не смог, но продолжаю работу над ним.

**Comment by SkivHisink** [comment]
Все данные ссылки исследованы.
